### ISSUE TITLE
v1 Release checklist

### ISSUE THREAD

**Issue by arshbot** [thesis/lnt#29]
v1.0.0 release checklist

- [ ] Kill zombie channels
- [ ] View channel by id ( search across APIs ) for LND knowledge of chan
- [ ] View incoming payments
- [ ] Migrate over to /arshbot/lnt
